# Generated by Django 4.2.7 on 2026-03-09 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='expenses_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('office', 'Office Supplies'), ('lunch', 'Business Lunch'), ('travel', 'Travel Expenses'), ('dinner', 'Client Dinner'), ('hotel', 'Hotel'), ('software', 'Software'), ('hardware', 'Hardware'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='team',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('IT', 'IT'), ('HR', 'HR'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingtask',
            name='task_type',
            field=models.CharField(choices=[('printing', 'Printing Approvals'), ('trips', 'New Trips Registered'), ('unreported', 'Unreported Expenses'), ('upcoming', 'Upcoming Expenses'), ('advances', 'Unreported Advances')], max_length=50, unique=True),
        ),
    ]
