# Generated by Django 4.2.7 on 2026-03-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='pdf_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='api.pdfupload'),
        ),
    ]
